### PR TITLE
8 ball plugin

### PR DESCRIPTION
**Pull request by bigbenster702**
**Plugin Name: 8 ball**

**Plugin __Short__ Description: Adds a fun 8 ball that you can ask questions to!**

**Your Discord Tag: bigbenster702#1840**

**Your Discord ID: 345959027143999490**

### CODE REVIEW

**Comment by MyNameIsAutistic** [comment]
qbot uses client, not bot.

**Comment by bigbenster702** [comment]
> qbot uses client, not bot.

Oh, ops I will need to fix that.

**Comment by bigbenster702** [comment]
K fixed

**Comment by MyNameIsAutistic** [comment]
> K fixed

ok

**Comment by bigbenster702** [comment]
> Looks pretty good. This will most likely be merged when I merge the next batch of plugins.

Thanks! Also k.

**Pull request merged**
