### PR TITLE
Update avatar.js and add uptime.js

### PR DESCRIPTION
**Pull request by TheShadowGamer**
Added the ability to get people’s avatar using their username. And two new plugins. 

Plugin Name: Uptime Command

Plugin Short Description: Gets the uptime of the bot

Plugin Name: Moderation Commands

Plugin Short Description: Allows you to mute, kick, ban, and unmute people.

Your Discord Tag: TheShadowGamer45#0960

Your Discord ID: 685289305056477188

### CODE REVIEW

**Comment by TheShadowGamer** [comment]
I have also added an uptime command, github automatically added it to this pull request.

**Comment by TheShadowGamer** [comment]
So should I change it to ms?

**Comment by yogurtsyum** [comment]
I would recommend that, yeah. The ms package is probably maintained more because it has 50 million weekly downloads and humanize-time only has around 150.

**Comment by TheShadowGamer** [comment]
Alright I switched it over @yogurtsyum

**Comment by yogurtsyum** [comment]
Can you please update your pull request to use the format? @TheShadowGamer

**Comment by TheShadowGamer** [comment]
Plugin Name: Uptime Command

Plugin Short Description: Gets the uptime of the bot

Your Discord Tag: TheShadowGamer45#0960

Your Discord ID: 685289305056477188

**Comment by yogurtsyum** [comment]
And for the moderation commands?

**Comment by TheShadowGamer** [comment]
I never noticed it put it in this pull, my bad.

Plugin Name: Moderation Commands

Plugin Short Description: Allows you to mute, kick, ban, and unmute people.

Your Discord Tag: TheShadowGamer45#0960

Your Discord ID: 685289305056477188

**Pull request merged**
