### PR TITLE
qbot | getinfo Plugin

### PR DESCRIPTION
**Pull request by TypicallyShad**
**Plugin Name:**
getinfo

**Plugin __Short__ Description:**
Grabs information on a user, including group rank, user ID, etc.

**Your Discord Tag:**
Shad#3200

**Your Discord ID:**
298014369533657090

### CODE REVIEW

**Comment by yogurtsyum** [comment]
The command looks good, but please add a step where they add the license for your plugin into their project because the MIT License requires it.

**Comment by TypicallyShad** [comment]
All done!

**Comment by TypicallyShad** [comment]
All done!

**Comment by yogurtsyum** [comment]
Looks good! +1

**Pull request merged**
